CREATE TABLE STANOWISKO (
    ID_STANOWISKA INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_STANOWISKA PRIMARY KEY,
    NAZWA_STANOWISKA VARCHAR2(50) NOT NULL UNIQUE,
    MAX_PLACA        NUMBER(10,2) NOT NULL,
    MIN_PLACA        NUMBER(10,2) NOT NULL
);


CREATE TABLE KLIENT (
    ID_KLIENTA          INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_KLIENTA PRIMARY KEY,
    IMIE                VARCHAR2(30) NOT NULL,
    NAZWISKO            VARCHAR2(30) NOT NULL,
    WIEK                INTEGER NOT NULL,
    WYDATKI             NUMBER(10,2) DEFAULT 0    
);


CREATE TABLE PLACOWKA (
    ID_PLACOWKI       INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_PLACOWKI PRIMARY KEY,
    MIASTO            VARCHAR2(30) NOT NULL,
    ADRES             VARCHAR2(30) NOT NULL,
    ILOSC_PRACOWNIKOW INTEGER DEFAULT 0,
    ILOSC_POJAZDOW    INTEGER DEFAULT 0
);


CREATE TABLE SAMOCHOD (
    ID_POJAZDU           INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_POJAZDU PRIMARY KEY,
    MARKA                VARCHAR2(30) NOT NULL,
    MODEL                VARCHAR2(30) NOT NULL,
    ROK_PRODUKCJI        INTEGER NOT NULL,
    STATUS               VARCHAR2(30) DEFAULT 'w salonie'
                          CONSTRAINT CHK_STATUS_SAMOCHOD 
                          CHECK (STATUS IN ('w salonie', 'sprzedane', 'wypozyczone')),
    CENA_ZA_KUPNO        NUMBER(10,2),
    CENA_ZA_WYNAJEM      NUMBER(10,2),
    ID_PLACOWKI          INTEGER,
    FOREIGN KEY (ID_PLACOWKI) REFERENCES PLACOWKA (ID_PLACOWKI)
);



CREATE INDEX IDX_CENA_ZA_KUPNO ON SAMOCHOD(CENA_ZA_KUPNO);

CREATE INDEX IDX_CENA_ZA_WYNAJEM ON SAMOCHOD(CENA_ZA_WYNAJEM);


CREATE TABLE KOLIZJA (
    ID_KOLIZJI     INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_KOLIZJI PRIMARY KEY,
    DATA_KOLIZJI   DATE NOT NULL,
    ID_POJAZDU     INTEGER NOT NULL,
    FOREIGN KEY (ID_POJAZDU) REFERENCES SAMOCHOD (ID_POJAZDU)
);


CREATE TABLE PRACOWNIK (
    ID_PRACOWNIKA      INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_PRACOWNIKA PRIMARY KEY,
    IMIE               VARCHAR2(20) NOT NULL,
    NAZWISKO           VARCHAR2(30) NOT NULL,
    PENSJA             NUMBER(10,2) NOT NULL,
    NAZWA_STANOWISKA   VARCHAR2(50) NOT NULL,
    ID_PLACOWKI        INTEGER NOT NULL,
    FOREIGN KEY (ID_PLACOWKI) REFERENCES PLACOWKA (ID_PLACOWKI),
    FOREIGN KEY (NAZWA_STANOWISKA) REFERENCES STANOWISKO (NAZWA_STANOWISKA)
);

CREATE INDEX IDX_PENSJA ON PRACOWNIK(PENSJA);


CREATE TABLE SERWIS (
    ID_SERWISU          INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_SERWISU PRIMARY KEY,
    DATA_SERWISU        DATE NOT NULL,
    KOSZT               NUMBER(10,2) NOT NULL,
    TYP_SERWISU         VARCHAR2(30) NOT NULL,
    ID_POJAZDU          INTEGER NOT NULL,
    FOREIGN KEY (ID_POJAZDU) REFERENCES SAMOCHOD (ID_POJAZDU)
);


CREATE TABLE TRANSAKCJA (
    ID_TRANSAKCJI       INTEGER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 NOCACHE CONSTRAINT PK_ID_TRANSAKCJI PRIMARY KEY,
    DATA_TRANSAKCJI     DATE NOT NULL,
    STATUS_TRANSAKCJI   VARCHAR2(30) NOT NULL
                          CONSTRAINT CHK_STATUS_TRANSAKCJI 
                          CHECK (STATUS_TRANSAKCJI IN ('sprzedane', 'wypozyczone', 'koniec wypozyczenia')),
    ID_POJAZDU          INTEGER NOT NULL,
    ID_KLIENTA          INTEGER NOT NULL,
    FOREIGN KEY (ID_KLIENTA) REFERENCES KLIENT (ID_KLIENTA),
    FOREIGN KEY (ID_POJAZDU) REFERENCES SAMOCHOD (ID_POJAZDU)
);


CREATE TABLE UBEZPIECZENIE (
    ID_TRANSAKCJI             INTEGER NOT NULL PRIMARY KEY,
    NAZWA                     VARCHAR2(30) DEFAULT 'nieokreslone'
                               CONSTRAINT CHK_NAZWA_UBEZPIECZENIA 
                               CHECK (NAZWA IN ('nieokreslone', 'OC', 'AC', 'Assistance')),
    CENA_UBEZPIECZENIA        NUMBER(10,2) DEFAULT 0,
    DATA_ZAWARCIA             DATE,
    DATA_ZAKONCZENIA          DATE,
    CZAS_TRWANIA_W_MIESIACACH INTEGER DEFAULT 0,
    STATUS_UBEZPIECZENIA      VARCHAR2(30) DEFAULT 'nieokreslone',
                               CONSTRAINT CH_STATUS_UBEZPIECZENIA
                               CHECK (STATUS_UBEZPIECZENIA IN ('nieokreslone', 'aktywne', 'nieaktywne')),
    FOREIGN KEY (ID_TRANSAKCJI) REFERENCES TRANSAKCJA (ID_TRANSAKCJI)
);


CREATE TABLE PLATNOSC (
    ID_TRANSAKCJI           INTEGER NOT NULL PRIMARY KEY,
    RODZAJ_PLATNOSCI        VARCHAR2(30) DEFAULT 'nieokreslone'
                              CONSTRAINT CHK_RODZAJ_PLATNOSCI 
                              CHECK (RODZAJ_PLATNOSCI IN ('nieokreslone', 'gotowka', 'karta platnicza')),
    KWOTA_ZAPLACONA         NUMBER(10,2) DEFAULT 0,
    FOREIGN KEY (ID_TRANSAKCJI) REFERENCES TRANSAKCJA (ID_TRANSAKCJI)
);



CREATE OR REPLACE FUNCTION update_ilosc_pracownikow (
    p_id_placowki IN PRACOWNIK.ID_PLACOWKI%TYPE,
    p_old_id_placowki IN PRACOWNIK.ID_PLACOWKI%TYPE,
    p_operation IN VARCHAR2
) RETURN VARCHAR2 IS
BEGIN
    IF p_operation = 'INSERT' THEN
        -- Dodanie pracownika do placówki
        UPDATE PLACOWKA
        SET ILOSC_PRACOWNIKOW = ILOSC_PRACOWNIKOW + 1
        WHERE ID_PLACOWKI = p_id_placowki;
    
    ELSIF p_operation = 'DELETE' THEN
        -- Usunięcie pracownika z placówki
        UPDATE PLACOWKA
        SET ILOSC_PRACOWNIKOW = ILOSC_PRACOWNIKOW - 1
        WHERE ID_PLACOWKI = p_old_id_placowki;
    
    ELSIF p_operation = 'UPDATE' THEN
        -- Zmiana placówki dla pracownika
        IF p_old_id_placowki != p_id_placowki THEN
        
            UPDATE PLACOWKA
            SET ILOSC_PRACOWNIKOW = ILOSC_PRACOWNIKOW - 1
            WHERE ID_PLACOWKI = p_old_id_placowki;

            UPDATE PLACOWKA
            SET ILOSC_PRACOWNIKOW = ILOSC_PRACOWNIKOW + 1
            WHERE ID_PLACOWKI = p_id_placowki;
        END IF;
    END IF;

    RETURN 'OK';
END;
/


CREATE OR REPLACE TRIGGER TRG_UPDATE_ILOSC_PRACOWNIKOW
AFTER INSERT OR DELETE OR UPDATE ON PRACOWNIK
FOR EACH ROW
DECLARE
    v_result VARCHAR2(100);
BEGIN
    IF INSERTING THEN
        v_result := update_ilosc_pracownikow(:NEW.ID_PLACOWKI, NULL, 'INSERT');
    ELSIF DELETING THEN
        v_result := update_ilosc_pracownikow(NULL, :OLD.ID_PLACOWKI, 'DELETE');
    ELSIF UPDATING THEN
        v_result := update_ilosc_pracownikow(:NEW.ID_PLACOWKI, :OLD.ID_PLACOWKI, 'UPDATE');
    END IF;
END;
/



CREATE OR REPLACE PROCEDURE update_ilosc_pojazdow (
p_status IN SAMOCHOD.STATUS%TYPE,
p_old_status IN SAMOCHOD.STATUS%TYPE,
p_id_placowki IN SAMOCHOD.ID_PLACOWKI%TYPE,
p_old_id_placowki IN SAMOCHOD.ID_PLACOWKI%TYPE,
p_operation IN VARCHAR2
) IS
BEGIN
    IF p_operation = 'INSERT' THEN
        IF p_status = 'w salonie' then
            -- Dodanie pojazdu do placówki
            UPDATE PLACOWKA
            SET ILOSC_POJAZDOW = ILOSC_POJAZDOW + 1
            WHERE ID_PLACOWKI = p_id_placowki;
        END IF;

    ELSIF p_operation = 'DELETE' THEN
        IF p_old_status = 'w salonie' THEN
            -- Usunięcie pojazdu z placówki
            UPDATE PLACOWKA
            SET ILOSC_POJAZDOW = ILOSC_POJAZDOW - 1
            WHERE ID_PLACOWKI = p_old_id_placowki;
        END IF;

    ELSIF p_operation = 'UPDATE' THEN

        IF p_old_id_placowki = p_id_placowki THEN
            IF p_old_status = 'w salonie' AND p_status != 'w salonie' THEN
                UPDATE PLACOWKA
                SET ILOSC_POJAZDOW = ILOSC_POJAZDOW - 1
                WHERE ID_PLACOWKI = p_id_placowki;
            END IF;

            ELSE IF p_old_status != 'w salonie' AND p_status = 'w salonie' THEN
                UPDATE PLACOWKA
                SET ILOSC_POJAZDOW = ILOSC_POJAZDOW + 1
                WHERE ID_PLACOWKI = p_id_placowki;
            END IF;
        END IF;
        -- Zmiana placówki dla pojazdu
        IF p_old_id_placowki != p_id_placowki THEN

            IF p_status = 'w salonie' THEN
                UPDATE PLACOWKA
                SET ILOSC_POJAZDOW = ILOSC_POJAZDOW - 1
                WHERE ID_PLACOWKI = p_old_id_placowki;

                UPDATE PLACOWKA
                SET ILOSC_POJAZDOW = ILOSC_POJAZDOW + 1
                WHERE ID_PLACOWKI = p_id_placowki;
            END IF;
            
        END IF;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_INSERT_CENA_ZA_WYNAJEM
BEFORE INSERT ON SAMOCHOD
FOR EACH ROW
BEGIN
  :NEW.CENA_ZA_WYNAJEM := :NEW.CENA_ZA_KUPNO * 0.01;
END;
/

CREATE OR REPLACE TRIGGER TRG_INSERT_CENA_ZA_WYNAJEM
BEFORE INSERT ON SAMOCHOD
FOR EACH ROW
BEGIN
  :NEW.CENA_ZA_WYNAJEM := :NEW.CENA_ZA_KUPNO * 0.01;
END;
/

CREATE OR REPLACE TRIGGER TRG_UPDATE_ILOSC_POJAZDOW
AFTER INSERT OR DELETE OR UPDATE ON SAMOCHOD
FOR EACH ROW
DECLARE
    v_operation VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operation := 'INSERT';
        -- Wywołanie procedury przy wstawieniu pojazdu
        update_ilosc_pojazdow(:NEW.STATUS, NULL, :NEW.ID_PLACOWKI, NULL, v_operation);
    ELSIF DELETING THEN
        v_operation := 'DELETE';
        -- Wywołanie procedury przy usuwaniu pojazdu
        update_ilosc_pojazdow(NULL, :OLD.STATUS, NULL, :OLD.ID_PLACOWKI, v_operation);
    ELSIF UPDATING THEN
        v_operation := 'UPDATE';
        -- Wywołanie procedury przy aktualizacji pojazdu
        update_ilosc_pojazdow(:NEW.STATUS, :OLD.STATUS, :NEW.ID_PLACOWKI, :OLD.ID_PLACOWKI, v_operation);

    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_USUN_PRACOWNIKOW
BEFORE DELETE ON STANOWISKO
FOR EACH ROW
BEGIN
    DELETE FROM PRACOWNIK
    WHERE NAZWA_STANOWISKA = :OLD.NAZWA_STANOWISKA;
END;
/


CREATE OR REPLACE TRIGGER TRG_SAMOCHOD_STATUS
AFTER INSERT ON TRANSAKCJA
FOR EACH ROW
DECLARE
    v_status VARCHAR2(20);
    v_id_pojazdu NUMBER;
    v_counter NUMBER;
BEGIN

    
    -- wywola sie exception no_data_found gdy nie ma takiego id_pojazdu
    SELECT ID_POJAZDU INTO v_id_pojazdu
    FROM SAMOCHOD 
    WHERE ID_POJAZDU = :NEW.ID_POJAZDU;

    SELECT STATUS INTO v_status 
    FROM SAMOCHOD 
    WHERE ID_POJAZDU = :NEW.ID_POJAZDU;

    

    IF v_status != 'w salonie' THEN
        RAISE_APPLICATION_ERROR(-20007, 'Nie mozesz dokonac transakcji samochodu, ktory nie znajduje sie w salonie');

    ELSIF :NEW.STATUS_TRANSAKCJI = 'sprzedane' THEN
        UPDATE SAMOCHOD
        SET STATUS = 'sprzedane'
        WHERE ID_POJAZDU = :NEW.ID_POJAZDU;

        INSERT INTO PLATNOSC (ID_TRANSAKCJI)
        VALUES(:NEW.ID_TRANSAKCJI);

    ELSIF :NEW.STATUS_TRANSAKCJI = 'wypozyczone' THEN
        UPDATE SAMOCHOD
        SET STATUS = 'wypozyczone'
        WHERE ID_POJAZDU = :NEW.ID_POJAZDU;
        
        INSERT INTO UBEZPIECZENIE (ID_TRANSAKCJI, DATA_ZAWARCIA)
        VALUES(:NEW.ID_TRANSAKCJI, NULL);

    ELSE
        RAISE_APPLICATION_ERROR(-20010, 'Wystapil blad podczas wstawniania pojazdu');
    END IF;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20008, 'Nie ma pojazdu o podanym przez ciebie ID ' || :NEW.ID_POJAZDU);
    
END;
/



CREATE OR REPLACE TRIGGER TRG_DELETE_TRANSAKCJA
BEFORE DELETE ON TRANSAKCJA
FOR EACH ROW
BEGIN

    IF :OLD.STATUS_TRANSAKCJI = 'wypozyczone' OR :OLD.STATUS_TRANSAKCJI = 'koniec wypozyczenia' THEN
        UPDATE KLIENT
            SET WYDATKI = WYDATKI - (SELECT KWOTA_ZAPLACONA FROM PLATNOSC 
                                     WHERE ID_TRANSAKCJI = :OLD.ID_TRANSAKCJI)
                                  - (SELECT CENA_UBEZPIECZENIA FROM UBEZPIECZENIE
                                     WHERE ID_TRANSAKCJI = :OLD.ID_TRANSAKCJI)
        WHERE ID_KLIENTA = :OLD.ID_KLIENTA;
    ELSE
        UPDATE KLIENT
            SET WYDATKI = WYDATKI - (SELECT KWOTA_ZAPLACONA FROM PLATNOSC 
                                     WHERE ID_TRANSAKCJI = :OLD.ID_TRANSAKCJI)
        WHERE ID_KLIENTA = :OLD.ID_KLIENTA;
    END IF;

    IF :OLD.STATUS_TRANSAKCJI = 'wypozyczone' THEN
        DELETE FROM UBEZPIECZENIE 
        WHERE ID_TRANSAKCJI = :OLD.ID_TRANSAKCJI;
    END IF;

    DELETE FROM PLATNOSC 
    WHERE ID_TRANSAKCJI = :OLD.ID_TRANSAKCJI;
END;
/


CREATE OR REPLACE TRIGGER TRG_KONIEC_WYPOZYCZENIA_SAMOCHODU
AFTER UPDATE ON TRANSAKCJA
FOR EACH ROW
BEGIN
    IF :NEW.STATUS_TRANSAKCJI = 'koniec wypozyczenia' THEN
        UPDATE SAMOCHOD
           SET STATUS = 'w salonie'
        WHERE ID_POJAZDU = :NEW.ID_POJAZDU;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_SET_KWOTA_ZAPLACONA
BEFORE UPDATE ON PLATNOSC
FOR EACH ROW
DECLARE
    V_STATUS_TRANSAKCJI VARCHAR2(30);
    V_CENA NUMBER(10,2);
    V_CZAS_TRWANIA_W_MIESIACACH NUMBER(10,2);
    V_RODZAJ_PLATNOSCI VARCHAR(255);
BEGIN

    V_RODZAJ_PLATNOSCI := :OLD.RODZAJ_PLATNOSCI;

    IF V_RODZAJ_PLATNOSCI = 'karta platnicza' OR V_RODZAJ_PLATNOSCI = 'gotowka' THEN
        RETURN;
    END IF;

    SELECT T.STATUS_TRANSAKCJI
    INTO V_STATUS_TRANSAKCJI
    FROM TRANSAKCJA T
    WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI;

    IF V_STATUS_TRANSAKCJI = 'sprzedane' THEN
        SELECT S.CENA_ZA_KUPNO
        INTO V_CENA
        FROM SAMOCHOD S JOIN TRANSAKCJA T ON T.ID_POJAZDU = S.ID_POJAZDU
        WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI;

    ELSIF V_STATUS_TRANSAKCJI = 'wypozyczone' THEN
        SELECT S.CENA_ZA_WYNAJEM
        INTO V_CENA
        FROM SAMOCHOD S JOIN TRANSAKCJA T ON T.ID_POJAZDU = S.ID_POJAZDU
        WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI;
    ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Blad podczas platnosci');
    END IF;
    
    
    IF V_STATUS_TRANSAKCJI = 'wypozyczone' THEN
        SELECT czas_trwania_w_miesiacach INTO V_CZAS_TRWANIA_W_MIESIACACH from ubezpieczenie where id_transakcji = :new.id_transakcji;

        V_CENA := V_CENA * V_CZAS_TRWANIA_W_MIESIACACH;
    END IF;

    :NEW.KWOTA_ZAPLACONA := V_CENA;

    UPDATE KLIENT
        SET WYDATKI = NVL(WYDATKI, 0) + V_CENA
        WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                            FROM TRANSAKCJA T 
                            WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);

END;
/


CREATE OR REPLACE TRIGGER TRG_SET_CENA_UBEZPIECZENIA
BEFORE UPDATE OF NAZWA ON UBEZPIECZENIE
FOR EACH ROW
DECLARE
    CENA_KUPNA NUMBER(10, 2);
    STATUS VARCHAR(30);
BEGIN

    IF :NEW.STATUS_UBEZPIECZENIA = 'nieaktywne' THEN
        RETURN;
    END IF;
   
    SELECT S.CENA_ZA_KUPNO, T.STATUS_TRANSAKCJI
    INTO CENA_KUPNA, STATUS
    FROM SAMOCHOD S JOIN TRANSAKCJA T ON S.ID_POJAZDU = T.ID_POJAZDU
    WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI;

    IF STATUS = 'sprzedane' THEN
        IF :NEW.NAZWA = 'OC' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 1;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 1
            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);

        ELSIF :NEW.NAZWA = 'Assistance' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 2;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 2
            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);

        ELSIF :NEW.NAZWA = 'AC' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 3;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.005 * CENA_KUPNA * 3

            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);
        ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Niepoprawna nazwa ubezpieczenia');
        END IF;
    END IF;
    
    IF STATUS = 'wypozyczone' THEN
        IF :NEW.NAZWA = 'OC' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 1;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 1
            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);

        ELSIF :NEW.NAZWA = 'Assistance' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 2;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 2
            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);

        ELSIF :NEW.NAZWA = 'AC' THEN
            :NEW.CENA_UBEZPIECZENIA := :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 3;
            UPDATE KLIENT
            SET WYDATKI = NVL(WYDATKI, 0) + :NEW.CZAS_TRWANIA_W_MIESIACACH * 0.0005 * CENA_KUPNA * 3
            WHERE ID_KLIENTA = (SELECT T.ID_KLIENTA 
                                FROM TRANSAKCJA T 
                                WHERE T.ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI);
        ELSE
            RAISE_APPLICATION_ERROR(-20001, 'Niepoprawna nazwa ubezpieczenia');
        END IF;

        :NEW.STATUS_UBEZPIECZENIA := 'aktywne';
        :NEW.DATA_ZAKONCZENIA := ADD_MONTHS(:NEW.DATA_ZAWARCIA, :NEW.CZAS_TRWANIA_W_MIESIACACH);

    END IF;

    INSERT INTO PLATNOSC (ID_TRANSAKCJI)
        VALUES(:NEW.ID_TRANSAKCJI);
END;
/


CREATE OR REPLACE TRIGGER TRG_STATUS_UBEZPIECZENIA
BEFORE UPDATE OF STATUS_UBEZPIECZENIA ON UBEZPIECZENIE
FOR EACH ROW
BEGIN
    IF :NEW.STATUS_UBEZPIECZENIA = 'nieaktywne' THEN
        UPDATE TRANSAKCJA
            SET STATUS_TRANSAKCJI = 'koniec wypozyczenia'
        WHERE ID_TRANSAKCJI = :NEW.ID_TRANSAKCJI;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_VALIDATE_PRACOWNIK_PENSJE
BEFORE INSERT OR UPDATE ON PRACOWNIK
FOR EACH ROW
DECLARE
    v_min_placa  NUMBER;
    v_max_placa  NUMBER;
BEGIN
    SELECT min_placa, max_placa
    INTO v_min_placa, v_max_placa
    FROM STANOWISKO
    WHERE NAZWA_STANOWISKA = :NEW.NAZWA_STANOWISKA;

    IF :NEW.PENSJA NOT BETWEEN v_min_placa AND v_max_placa THEN
        RAISE_APPLICATION_ERROR(-20002, 'Pensja musi mieścić się w zakresie od ' || v_min_placa || ' do ' || v_max_placa || ' dla stanowiska: ' || :NEW.NAZWA_STANOWISKA);
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_NAZWA_PLACOWKI
BEFORE INSERT ON PLACOWKA
FOR EACH ROW
DECLARE
    v_count INTEGER;
BEGIN
    
    SELECT COUNT(*)
    INTO v_count
    FROM PLACOWKA
    WHERE MIASTO = :NEW.MIASTO
    AND ADRES = :NEW.ADRES;

    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Placowka znajduje sie juz w wybranej lokalizacji');
    END IF;
END;
/


CREATE OR REPLACE TRIGGER TRG_NAZWA_STANOWISKA
BEFORE INSERT ON STANOWISKO
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM STANOWISKO 
    WHERE NAZWA_STANOWISKA = :NEW.NAZWA_STANOWISKA;
    
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Podana nazwa stanowiska ' || :NEW.NAZWA_STANOWISKA || ' już istnieje');
    END IF;

END;
/


CREATE OR REPLACE TRIGGER TRG_UPDATE_STANOWISKO
BEFORE UPDATE OF NAZWA_STANOWISKA ON STANOWISKO
FOR EACH ROW
BEGIN    
    UPDATE PRACOWNIK
        SET NAZWA_STANOWISKA = :NEW.NAZWA_STANOWISKA
        WHERE NAZWA_STANOWISKA = :OLD.NAZWA_STANOWISKA;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20005, 'Nie możesz modyfikowac nazwy stanowiska w ktorej sa pracownicy');
            NULL;
END;
/


CREATE OR REPLACE TRIGGER TRG_SERWIS_ID_POJAZDU
BEFORE INSERT ON SERWIS
FOR EACH ROW
DECLARE
    v_id_pojazdu NUMBER;
BEGIN
    SELECT ID_POJAZDU INTO v_id_pojazdu
    FROM SAMOCHOD
    WHERE ID_POJAZDU = :NEW.ID_POJAZDU;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'Nie ma pojazdu o podanym przez ciebie ID ' || :NEW.ID_POJAZDU);
END;
/


CREATE OR REPLACE TRIGGER TRG_KOLIZJA_ID_POJAZDU
BEFORE INSERT ON KOLIZJA
FOR EACH ROW
DECLARE
    v_id_pojazdu NUMBER;
BEGIN
    SELECT ID_POJAZDU INTO v_id_pojazdu
    FROM SAMOCHOD
    WHERE ID_POJAZDU = :NEW.ID_POJAZDU;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20008, 'Nie ma pojazdu o podanym przez ciebie ID ' || :NEW.ID_POJAZDU);
END;
/